name: revolt_client
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0-207.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  copy_with_extension: ^5.0.4
  freezed_annotation: ^2.0.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  shared_preferences: 2.3.1
  web_socket_channel: ^3.0.1
  uuid: ^4.5.1
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.5
  copy_with_extension_gen: ^5.0.4
  json_serializable: ^6.0.1
  lints: ^5.1.0
  mockito: ^5.0.16
  test: ^1.16.0
  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
